model:
  name: 'DPN3D'
loss:
  name: 'CrossEntropy'
dataset:
  normalize:
    mean: 178.83227827824444
    std:  50.05896544303765
train_params:
  batch_size: 4
  n_epochs: 300
  ckpt_every: 150
  init_lr: 0.1
  lr_decay: 0.1
  decay_epochs: [50, 100, 150, 200]