model:
  name: 'NAS'
  params:
    config: [[4,4], [4,8], [8,8]]
loss: 'AngleLoss'
dataset:
  normalize:
    mean: 178.83227827824444
    std:  50.05896544303765
train_params:
  batch_size: 4
  n_epochs: 420
  ckpt_every: 80
  init_lr: 0.002
  lr_decay: 0.1
  decay_epochs: [140,280]